repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.1
    hooks:
      - id: pre-commit-update
        args: [--dry-run]
  - repo: https://github.com/spyderbat/spyder-scan
    rev: v1.1.1
    hooks:
      - id: spyder-scan
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'docker run  -v "$(pwd):/workdir" ghcr.io/trufflesecurity/trufflehog:latest --no-verification git file:///workdir --debug --fail --exclude-paths /workdir/exclude-patterns.txt'
        language: system
        stages: ["commit", "push"]
