target-version = "py313"
src = ["spyctl"]
[lint]
extend-select = ["F", "E", "W", "N", "B", "S", "I", "TD002", "ANN", "LOG", "RUF", "PLE", "ASYNC", "FAST"]
ignore = ["E501", "ASYNC109", "S101", "S311"]
[lint.isort]
known-first-party = ["spyctl"]