name: Spyctl API Build & Deploy
on:
  push:
    branches: [integration_api, staging_api, production_api]

jobs:
  integration-build:
    if: github.ref_name == 'integration_api'
    uses: ./.github/workflows/reusable-build-deploy.yaml
    with:
      deployment: integration
      environment: integration_api
    secrets: inherit

  integration2-build:
    if: github.ref_name == 'integration_api'
    uses: ./.github/workflows/reusable-build-deploy.yaml
    with:
      deployment: integration2
      environment: integration2_api
    secrets: inherit

  staging-build:
    if: github.ref_name == 'staging_api'
    uses: ./.github/workflows/reusable-build-deploy.yaml
    with:
      deployment: staging
      environment: staging_api
    secrets: inherit

  prod-build:
    if: github.ref_name == 'production_api'
    uses: ./.github/workflows/reusable-build-deploy.yaml
    with:
      deployment: prod
      environment: prod_api
    secrets: inherit

  mum-prod-build:
    if: github.ref_name == 'production_api'
    uses: ./.github/workflows/reusable-build-deploy.yaml
    with:
      deployment: mum-prod
      environment: mum_prod_api
    secrets: inherit

  fa-prod-build:
    if: github.ref_name == 'production_api'
    uses: ./.github/workflows/reusable-build-deploy.yaml
    with:
      deployment: fa-prod
      environment: fa_prod_api
    secrets: inherit
