name: Format Checker

on:
  pull_request:

jobs:
  black-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Black
        run: pip install black

      - name: Check Black formatting
        run: ./black.sh --check
  isort-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install isort
        run: pip install isort

      - name: Check isort formatting
        run: isort --check --profile black --filter-files --skip-gitignore .
