name: Format Checker

on:
  pull_request:

jobs:
  ruff-lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Run ruff lint check
        run: ./ruff-lint.sh --check