name: Publish Spyctl to TestPyPI

on: 
  release:
    types: [published]

jobs:
  build:
    if: startsWith(github.event.release.tag_name, 'v') && contains(github.event.release.tag_name, 'beta') && github.event.release.target_commitish == 'develop'
    name: Build Spyctl distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish Spyctl distribution to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/spyctl
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
    - name: Notify Slack
      run: |
        curl -request POST \
          --header 'Content-type: application/json' \
          --url ${{ secrets.RELEASE_CHANNEL_WEBHOOK }} \
          --data '{"text": "*Spyctl CLI ${{github.event.release.tag_name}}* released to *Test Pypi*. *Author*: ${{ github.actor }} "}'
    - name: Failure
      if: failure()
      run: |
        echo "Notify Slack of failure"
        curl -request POST \
          --header 'Content-type: application/json' \
          --url ${{ secrets.RELEASE_CHANNEL_WEBHOOK }} \
          --data '{"text": "*Spyctl CLI ${{github.event.release.tag_name}}* released to *Test Pypi* failed."}'


